dbt_backstage:
  target: ci
  outputs:
    ci:
      type: postgres
      host: "{{ env_var('DBT_DB_HOST') }}"
      port: "{{ env_var('DBT_DB_PORT') | int }}"
      user: "{{ env_var('DBT_CI_USER') }}"
      password: "{{ env_var('DBT_CI_PASSWORD') }}"
      dbname: "{{ env_var('DBT_DB_NAME') }}"
      schema: "{{ env_var('DBT_CI_SCHEMA') }}"
      threads: 4
      keepalives_idle: 0
    prod:
      type: postgres
      host: "{{ env_var('DBT_DB_HOST') }}"
      port: "{{ env_var('DBT_DB_PORT') | int }}"
      user: "{{ env_var('DBT_PROD_USER') }}"
      password: "{{ env_var('DBT_PROD_PASSWORD') }}"
      dbname: "{{ env_var('DBT_DB_NAME') }}"
      schema: "{{ env_var('DBT_PROD_SCHEMA') }}"
      threads: 4
      keepalives_idle: 0